export const ACTION_LABELS = {
  "auth.signed_in": "Signed in",
  "auth.signed_out": "Signed out",
  "allocation.created": "Allocation created",
  "allocation.updated": "Allocation edited",
  "allocation.deleted": "Allocation deleted",
  "transfer.created": "Transfer recorded",
  "plot.reserved": "Plot reserved",
  "plot.updated": "Plot edited",
  "user.created": "Staff created",
  "user.role_updated": "Staff role updated",
  "user.deleted": "Staff removed",
  "client.created": "Client added",
  "client.updated": "Client edited",
  "client.deleted": "Client deleted",
  "document.uploaded": "Document uploaded",
  "document.updated": "Document edited",
  "document.deleted": "Document deleted",
};

export const ACTION_TONES = {
  "auth.signed_in": "bg-green-50 text-green-700",
  "auth.signed_out": "bg-slate-100 text-slate-600",
  "allocation.created": "bg-green-50 text-green-700",
  "allocation.updated": "bg-purple-50 text-purple-700",
  "allocation.deleted": "bg-red-50 text-red-700",
  "transfer.created": "bg-navy-50 text-navy-700",
  "plot.reserved": "bg-amber-50 text-amber-700",
  "plot.updated": "bg-purple-50 text-purple-700",
  "user.created": "bg-green-50 text-green-700",
  "user.role_updated": "bg-navy-50 text-navy-700",
  "user.deleted": "bg-red-50 text-red-700",
  "client.created": "bg-green-50 text-green-700",
  "client.updated": "bg-purple-50 text-purple-700",
  "client.deleted": "bg-red-50 text-red-700",
  "document.uploaded": "bg-green-50 text-green-700",
  "document.updated": "bg-purple-50 text-purple-700",
  "document.deleted": "bg-red-50 text-red-700",
};
